### ISSUE TITLE
Icon for hunter trap is missing

### ISSUE THREAD

**Issue by Painstormx** [Toludin/ClassMods#1]
When you place a Freezing Trap, there used to be an icon showing a timer when the trap expired.
That icon is now missing (it's the Crown Control bar).

**Comment by Lotan21** [comment]
The issue seems to be in the function on line 178 in crowdcontrol.lua where the none of the if statements ever trigger.

**Comment by Toludin** [comment]
Thanks for the report, guys. Yea, crowdcontrol.lua has to be updated to the new CombatLogGetCurrentEventInfo() call. I'll make that change tonight.

**Comment by Toludin** [comment]
This issue, along with a few others (auto attack timer bar, totems, and announcements) should be fixed. Will leave this open so people can test first :)

**Comment by Painstormx** [comment]
Just tested it on my hunter and it seems to be working decently.
At one point I got an extra Freezing Trap icon though, when there were 5-10 seconds left on the original one.
The original icon expired, mob got freed and then the 2nd icon started counting down.
Can't seem to replicate it though, so no big deal.

**Comment by Toludin** [comment]
Going to close this out for now, please open it again if you see this crop up.
