### ISSUE TITLE
LUA errors for frost mage

### ISSUE THREAD

**Issue by Painstormx** [Toludin/ClassMods#2]
On my frost mage, the error below pops up randomly in combat.
After a short while, I got other addons telling me that there are now 1000+ errors LUA errors and that error reporting will stop.

Date: 2018-08-01 14:55:20
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ClassMods\modules\resourcebar.lua line 546:
   attempt to compare number with string
Debug:
   [C]: ?
   ClassMods\modules\resourcebar.lua:546: checkFunction()
   ClassMods\modules\resourcebar.lua:698:
      ClassMods\modules\resourcebar.lua:691
Locals:

EDIT: Just got the same error on my balance druid when activating Travel Form

**Comment by Toludin** [comment]
Believe I fixed the Frost Mage one, though I noticed (even without my fix) that most of the stack tracking doesn't appear to be working right now. But Ice Block does work now.

Let me know if you still see it on Frost Mage. I'll keep looking into Druid tomorrow.

**Comment by Painstormx** [comment]
Tried the new version.
It seems a bit random what triggers the error.
I tried on frost mage again and this time it was triggered by Ice Floes.
However, I did a /reloadui and couldn't reproduce it with Ice Floes :(

**Comment by Painstormx** [comment]
Any updates on the mage/druid errors?
The druid one seems to be pretty consistent.
If you after combat use travel form, it pops up most of the time.

**Comment by Toludin** [comment]
Taking a look.

**Comment by Toludin** [comment]
Can you give the new version a test? Also found a related issue where aura-type stack tracking (like for Lunar/Solar empowerment) wasn't working correctly. I think both issues are fixed.

**Comment by Painstormx** [comment]
Just quested a bit including a lot of shape shifting.
Didn't encounter any bugs, so awesome work :D
